### ISSUE TITLE
can we please have a sample app

### ISSUE THREAD

**Issue by touseefbsb** [ZhaoYunxiong/libVLCX.UWP#1]
Can we Please have a sample UWP app with MediaPlayerElement showing how to consume libVLC.UWp library into our apps to play video and audio files,?Because it will make easier for developers on how to actually use this library in their own uwp media projects. Thanks.

**Comment by ZhaoYunxiong** [comment]
Ok, I will do this as soon as possible when I'm free

**Comment by touseefbsb** [comment]
@ZhaoYunxiong  sure ill be looking forward to it :)

**Comment by ZhaoYunxiong** [comment]
@touseefbsb  I uploaded a simple app [SampleApp1](https://github.com/ZhaoYunxiong/libVLCX.UWP/tree/master/SampleApp1)

**Comment by touseefbsb** [comment]
@ZhaoYunxiong  Really appreciated. Thanks :)
